### ISSUE TITLE
Back - Ajout de points de passage

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#10]
## User stories
Un utilisateur, à travers l'api, peut ajouter un nouveau point de passage à un projet

## Description of needs _Optional_
La création [d'un point de passage](https://excalidraw.com/#room=2801f4fad8f9503c60ad,jiWzsiP-U-eTB2sXkmj2Jg) doit prendre en compte : 
- Trip Id*
- Name*
- StarDate*
- EndDate*
- Description
- Latitude*
- Longitude*
_Pas besoins ici de prendre en compte les reservations, elle seront ajouter par la suite_
_Pas besoin de prendre en charge le travelTo pour l'instant ce seras pris en charge par la suite_

## Acceptance criteria (done when...)

_**Tip**: Write a **checkboxed** list of sentences in the present tense describing the desired state of the system._

**GOOD (clear how to verify, it reports design and interaction decisions
agreed):**
- [ ] 

**BAD (cannot be activated during verification, too arbitrary):** _Optional_

- [ ] Prend en charge les reservation
- [ ] Prend en charge le travel to

## Tasks

- [ ] TDD
- [ ] Ajout endpoint de creation de step
- [ ] DTO de Step
- [ ] Validator Step
- [ ] Mapper Step
- [ ] Service Add Step
- [ ] Repository Add Step
