### ISSUE TITLE
Back - Requête global pour l'affichage des voyages de l'utilisateur en fonction des params

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#11]
## User stories
Un utilisateur peut filtrer ses voyages futurs en fonction de certains critères. Il peut filtrer par :
- date
- durée du voyage
- destination
- le budget

Coté back, il faut que ce soit une route unique qui nous renvoi les informations, les paramètres de la requête permettra de gérer les différents filtres appliqués et de gérer également la pagination. 
A voir: structure de la requête.
Il faudra donc renvoyer au front seulement les voyages correspondant à notre recherche.

## Tasks
* [ ] Création de la route API
* [ ] Création de l'appel du répository qui va donner les voyages correspondant
* [ ] Gérer le système de la route avec les params en méthode GET
