### ISSUE TITLE
Front - Un utilisateur peut avoir accès aux voyages qu'il a crée et qui ne sont pas dans le passée

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#12]
## User stories
Un utilisateur, sur un espace dédier au listing des voyages. Peut avoir accès a tous les voyages qu'il a crée, qui sont en cours ou dans le futur. Il est possible de filtrer les voyages en questions selon un ensemble de critères tel que le nom, des mots de la description, des dates, ou encore des pays en lien avec le voyage.

## Description of needs _Optional_
- Lister les voyages qui ne sont pas dans le passer
- Filtrer ces derniers selon différents critères

## Drafts or UI templates _Optional_
- Un composant qui représentera une card pour un voyage (voir les infos à afficher (image, titre, description et date ?)

## Acceptance criteria (done when...)

_**Tip**: Write a **checkboxed** list of sentences in the present tense describing the desired state of the system._

**GOOD (clear how to verify, it reports design and interaction decisions
agreed):**

- [ ] Lister l'ensemble des voyages
- [ ] Filtrer les voyages qui sont disponible selon différent critères
- [ ] Propose de rediriger vers la page d'historique si les filtre ne retourne aucune valeur 

**BAD (cannot be activated during verification, too arbitrary):** _Optional_
- [ ] Retourne des voyages qui sont terminer et donc dans le passer

## Tasks

_This section is populated by the developer and reports the expected practical activities to meet the requirements. Useful for estimating and for day-by-day monitoring. Better if it reports checkboxes to track completion._
