### ISSUE TITLE
Front - Profile

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#13]
## User stories
Un utilisateur connecté à accès à son profil de bord à partir du bouton de la navbar.
Nous retrouvons 5 sections dans cette page:
- Informations personnels 
- Changer de mot de passe
- Changer d'email
- CGU (redirection sur la page)
- Supprimer mon compte

Chacune des sections de cette page sont des formulaires avec certains prérempli pour edit les infos de l'utilisateur.

## Tasks
* [ ] Faire le composant comme afficher sur la maquette (avec la navLink)
* [ ] Créer les 4 composants de chaque section
* [ ] Créer les formulaires 
* [ ] Gestion des erreurs
 
#### Informations personnels 
* [ ]  Changer différentes de ses infos tels que le Prénom, le nom ou l'âge

#### Changer de mot de passe

- [ ] L'utilisateur fait une demmande de changement de mot de passe en confirmant email + mdp, si valide il resoit un lien dans sont mail. qui lui permet de reset le password.
~Changer son mot de passe soit en mettant son mdp actuel et s'il est correcte alors il peut changer son mot de passe avec une confirmation ou sinon un lien url est envoyé dans un email lui permettant de modifier (à voir comment on fait)~

#### Changer d'email
* [ ] Confirmer l'identité de l'utilisateur avec password
* [ ] Valider que l'e-mail saisi est valide et n'est pas déjà associé à un autre compte utilisateur.
* [ ] Envoyer un e-mail de confirmation ou un lien de validation à l'utilisateur pour confirmer le changement d'email

#### Supprimer le compte
* [ ] Confirmer l'identité de l'utilisateur avec password
* [ ] Mettre en place une fenêtre de confirmation pour demander à l'utilisateur de confirmer sa décision de suppression de compte.
* [ ] Mettre en place une double confirmation pour éviter une erreur de suppression
