### ISSUE TITLE
Front - Page de contact

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#14]
## User stories
Un utilisateur doit pouvoir accéder a la page de contact dans le footer, il retrouvera sur cette page des informations essentiels (adresse, email, numéro de téléphone etc...) et un formulaire de contact avec comme champ : 
- sujet de l'email
- objet de l'email
- corps de texte/description 
- bouton d'envoi 

Une fois complété, il a une notification en cas de succès ou non et recevra un email de confirmation de réception.

### Contrainte 
Afficher les erreurs de formulaires sur chaque input

### Idées
- Mettre une carte

## Tasks
* [x] Création du formulaire
* [x] Création de la page de contact avec mise en forme (voir maquette)
* [x] Gérer l'affichage des erreurs et des redirections 
* [x] Affichage des notifications une fois le formulaire soumis
