### ISSUE TITLE
Front - 2Fa

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#15]
## User stories
Un utilisateur doit renseigner un code a 6 chiffres pour pouvoir se connecter a son compte. Le code 2fa est envoyer sur son email qu'il a définit lors de l'enregistrement de son compte. 

Une fois complété, il est rediriger sur la page de son compte (si succès) et il a une notification en cas de succès ou non

Par default ce système est désactiver. Cependant l'utilisateur peut l'activier depuis son profil

Dès la première connexion de l'utilisateur. Une popUp informe l'utilisateur de l'existance de cette fonctionnalitée.
L'utilisateur peut faire le chois de : 

- être rediriger vers le params d'activation du 2fa
- fermer la popup
- Ne afficher l'information

### Contrainte 
Il ne peux que écrire des chiffres dans l'input + vérifier que le copier coller fonctionne bien

## Tasks
* [ ] Création du formulaire (input + bouton d'envoi)
* [ ] Création de la page 2fa avec mise en forme
* [ ] Gérer l'affichage des erreurs et des redirections 
* [ ] Affichage des notifications une fois le formulaire soumis
