### ISSUE TITLE
Front - Avis

### ISSUE THREAD

**Issue by BaptisteLegat** [From-A2B/WebApp#24]
# User stories
Un utilisateur peut avoir accès a la page des avis via le footer. Sur cette page, nous retrouvons 3 sections: 
- Un carrousel avec les commentaires de chaque utilisateur avec son nom, sa note et la date à laquelle il à rédiger l'avis 
- Note moyenne attribué par les utilisateurs
- Formulaire pour mettre un avis (commentaire et note)

## Contrainte
Il faut que l'utilisateur soit connecté pour mettre un avis.

# Task
* [ ] Calculer la note moyenne à partir des données récupérer de l'api
* [ ] Faire un composant Card qui contiendra chaque avis utilisateur et qui sera mis dans le carrousel
* [ ] Faire un composant (type étoile) pour mettre une note sur 5 (1 à 5)
* [ ] Créer et envoyer le formulaire avec les vérifications nécéssaires
