### ISSUE TITLE
Dockeriser l'application

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#3]
## User stories
Les devs doivent conteneuriser le front selon deux environment un premier de dev et un second de prod.
Le premier comprend l'ensemble des dépendances et du code nécessaire pour faire tourner l'application en local.
Le second comprend uniquement le code compiler près à être exécuter sur un serveur de production.

## Acceptance criteria (done when...)
- [ ] Le dockerfile permet de faire tourner l'application en local 
- [ ] Le dockerfile.Release permet de faire une image directement depuis des fichier compilé dans une pipeline CI

## Tasks
* [ ] Créer un Dockerfile pour le dev local du front
* [ ] Créer un Dockerfile.Release pour faire tourner le front sur un serveur de production
