### ISSUE TITLE
Un utilisateur peut crée un compte

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#4]
## US
Un nouvel utilisateur, peut crée un compte afin d'avoir accès à la platform. La création du compte est simple et rapide. L'utilisateur doit fournir un email, un mot de passe et un nom d'utilisateur. Une fois le compte crée l'utilisateur doit activer son compte en cliquant sur un lien envoyé par email.

## Description of needs
- L'utilisateur doit pouvoir s'inscrire en utilisant un email, un mot de passe et un nom d'utilisateur.
- L'utilisateur doit pouvoir activer son compte en cliquant sur un lien envoyé par email.

## Acceptance criteria (done when...)

- [x] L'email est valide
- [x] L'email est unique
- [x] Le mot de passe correspond aux critères de sécurité
- [x] Un deuxième champ pour confirmer le mot de passe est identique au premier
- [x] Le compte est activé après avoir cliqué sur le lien envoyé par email
- [x] Tant que le compte n'est pas activé, l'utilisateur n'as pas de privilèges

## Tasks
- [x] Crée un endpoint pour l'inscription
- [x] Crée un dto pour l'inscription
- [x] Crée un validator pour le dto
  - [x] L'email est valide
  - [x] L'email est unique
  - [x] Le mot de passe correspond aux critères de sécurité
  - [x] Le champ de confirmation est identique au premier
- [x] Crée un service pour l'inscription
- [x] Crée un utilisateur
- [x] Génère un token pour l'activation du compte
- [x] Envoie un email pour activer le compte
- [x] Crée un endpoint pour activer le compte
- [x] Crée un service pour activer le compte
- [x] Si le token est valide, ajouter le rôle USER à l'utilisateur
