### ISSUE TITLE
Front - CI CD

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#6]
## User stories
Les devs doivent pouvoir facilement déployer et faire tourner les applications sur différents environnement disponible en ligne. Pour celas ces dernier doivent crée des pipelines CI et CD pour automatiser l'ensemble. 

## Acceptance criteria (done when...)
- [ ] Les pipelines CI et CD sont construit en plusieurs Stages
- [ ] Les pipelines CI et CD sont construit en plusieurs Jobs
- [ ] Les pipelines CI et CD Compile le projet
- [ ] Les pipelines CI et CD font tourner les tests
- [ ] Les pipelines CI et CD build les images Docker depuis le code compiler
- [ ] Les pipelines CI et CD sont documentés

## Tasks
- [ ] CI Front
- [ ] CD Front
