### ISSUE TITLE
Front - un utilisateur peut se créer un compte

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#7]
## User stories
Un utilisateur doit pouvoir se créer un compte a partir de la page de register.
Il doit renseigner différentes informations pour se créer un compte : 
- email
- username
- mot de passe
- accepter les CGU

Une fois complété, il est rediriger sur la page de landing en cas de success et il a une notification en cas de succès ou non

### Contrainte 
Afficher les erreurs de formulaires sur chaque input

## Tasks
* [x] Création du formulaire
* [x] Création de la page d'enregistrement avec mise en forme
* [x] Gérer l'affichage des erreurs et des redirections 
* [x] Affichage des notifications une fois le formulaire soumis
