### ISSUE TITLE
Front - Tableau de bord

### ISSUE THREAD

**Issue by Dercraker** [From-A2B/WebApp#9]
## User stories
Un utilisateur connecté à accès à un tableau de bord à partir du bouton de la navbar.
Nous retrouvons 3 sections dans cette page:
- Liste des voyages 
- Historique des voyages (passées)
- Statistique

Sur la page _liste des futurs voyages_ des filtres sont disponibles pour l'utilisateur

## Tasks
* [ ] Faire le composant comme afficher sur la maquette (avec les 3 parties)
* [ ] Créer les 3 composants de chaque section
* [ ] Création du layout 
 
#### Statistique
* [ ] Mettre en place différentes statistique pouvant être intéressante pour l'utilisateur (Voir quel lib utiliser également), tel que le nombre de kilomètre parcourus, la quantité de kg de Co2 consommé, le nombre de jour de voyage...

#### Liste des voyages
* [ ] Créer un composant de type card qui représentera un voyage futur. Il y aura les informations essentiel le concernant et il pourra cliquer dessus pour accéder à la page de détail de son voyage.
* [ ] Créer des composants de filtres pour les critères de recherche tels que la destination, la date, le budget, etc.

#### Historique / terminer
* [ ] Permettre de renouveler un de ses anciens voyages pour éviter de le re créer a la main
